# Generated by Django 6.0.5 on 2026-05-23 12:22

import django.db.models.deletion
import image_osint.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=image_osint.models.image_upload_path)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('detected_format', models.CharField(blank=True, max_length=16)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('has_exif', models.BooleanField(default=False)),
                ('perceptual_hash', models.CharField(blank=True, max_length=32)),
                ('sha256_file', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Image analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
