# Generated by Django 6.0.7 on 2026-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whois_osint', '0004_remove_domainlookup_subdomain_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainlookup',
            name='zone_transfer_vulnerable',
            field=models.BooleanField(default=False),
        ),
    ]
