# Generated by Django 6.0.6 on 2026-07-04 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_input', models.CharField(db_index=True, max_length=253)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45)),
                ('ptr_hostname', models.CharField(blank=True, max_length=255)),
                ('asn', models.CharField(blank=True, max_length=32)),
                ('isp', models.CharField(blank=True, max_length=255)),
                ('org_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('is_proxy_or_vpn', models.BooleanField(default=False)),
                ('is_hosting', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_intel_lookups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'query_input'), name='ip_intel_user_query_uniq')],
            },
        ),
    ]
