# Generated by Django 6.0.6 on 2026-07-03 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgFootprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('org_name', models.CharField(blank=True, max_length=255)),
                ('org_country', models.CharField(blank=True, max_length=8)),
                ('whois_privacy', models.BooleanField(default=False)),
                ('spf_status', models.CharField(blank=True, max_length=16)),
                ('dmarc_status', models.CharField(blank=True, max_length=16)),
                ('dkim_selector_count', models.PositiveSmallIntegerField(default=0)),
                ('security_header_score', models.PositiveSmallIntegerField(default=0)),
                ('social_platform_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_footprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'domain'), name='org_footprint_user_domain_uniq')],
            },
        ),
    ]
