# Generated by Django 6.0.7 on 2026-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_footprint_osint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgfootprint',
            name='tls_days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
