# Generated by Django 6.0.5 on 2026-05-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
