# Generated by Django 6.0.6 on 2026-07-06 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_domain', models.CharField(db_index=True, max_length=253)),
                ('email_hint', models.CharField(blank=True, max_length=254)),
                ('username_hint', models.CharField(blank=True, max_length=64)),
                ('modules_run', models.JSONField(blank=True, default=list)),
                ('emails_checked', models.PositiveSmallIntegerField(default=0)),
                ('ips_checked', models.PositiveSmallIntegerField(default=0)),
                ('usernames_checked', models.PositiveSmallIntegerField(default=0)),
                ('overall_risk_level', models.CharField(default='low', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_domain'), name='investigation_user_domain_uniq')],
            },
        ),
    ]
