# Generated by Django 6.0.6 on 2026-07-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation_osint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='ai_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='ai_report_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='ai_report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='ai_report_model',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
