# Generated by Django 6.0.7 on 2026-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdomain_osint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainscan',
            name='live_host_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
