# Generated by Django 6.0.7 on 2026-07-18 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirBusterScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(db_index=True, max_length=512)),
                ('base_url', models.CharField(blank=True, max_length=512)),
                ('host', models.CharField(blank=True, max_length=253)),
                ('wordlist_tier', models.CharField(blank=True, max_length=16)),
                ('checked_count', models.PositiveSmallIntegerField(default=0)),
                ('found_count', models.PositiveSmallIntegerField(default=0)),
                ('redirect_count', models.PositiveSmallIntegerField(default=0)),
                ('forbidden_count', models.PositiveSmallIntegerField(default=0)),
                ('filtered_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dirbuster_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'target'), name='dirbuster_user_target_uniq')],
            },
        ),
    ]
